#!/bin/bash 

current_exercise_no=$(ls test/todo_app/*_tests.clj \
    | grep -oE "test/todo_app/[0-9]{2}_tests.clj" \
    | grep -oE "[0-9]{2}" \
    | sort \
    | tail -n 1)
next_exercise_no="$(printf "%02d" "$(( ${current_exercise_no} + 1 ))")"

lein test .

rc=$?
if [[ $rc != 0 ]]
then 
	echo "Try again before going on to the next exercise!"
	exit $rc; 
fi

echo "Retrieving exercise $next_exercise_no"

#(git checkout $(whoami) || git checkout -b $(whoami)) 2> /dev/null

#if ! git status | grep "nothin.*to commit" &> /dev/null
#then 
#  git add *.clj && git commit --allow-empty -anm "Commit exercise $(printf "%02d" ${current_exercise_no})"
#fi


#git fetch --all


#if ! git branch -a | grep "/origin/${next_exercise_no}" &> /dev/null
#then
#    echo "The next exercise is not yet available"
#    exit 1
#fi 

#git merge --no-ff -m "Fetching exercise ${next_exercise_no}" origin/${next_exercise_no}

#cat tutorial/chapters/${next_exercise_no}_instructions.md
